# Generated by Django 4.1.1 on 2022-09-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogid', models.BigIntegerField()),
                ('writerAge', models.CharField(max_length=20)),
                ('writerBlogNum', models.IntegerField()),
                ('writerCollect', models.IntegerField()),
                ('writerComment', models.IntegerField()),
                ('writerFan', models.IntegerField()),
                ('writerGrade', models.CharField(max_length=20)),
                ('writerIntegral', models.IntegerField()),
                ('writerName', models.TextField()),
                ('writerRankWeekly', models.IntegerField()),
                ('writerRankTotal', models.IntegerField()),
                ('writerProfileAdress', models.TextField()),
                ('writerThumb', models.BigIntegerField()),
                ('writerVisitNum', models.BigIntegerField()),
                ('blog_read_count', models.BigIntegerField()),
                ('blog_time', models.TextField()),
                ('blog_title', models.TextField()),
                ('content', models.TextField()),
                ('cpp', models.SmallIntegerField(default=0)),
                ('csharp', models.SmallIntegerField(default=0)),
                ('java', models.SmallIntegerField(default=0)),
                ('javascript', models.SmallIntegerField(default=0)),
                ('php', models.SmallIntegerField(default=0)),
                ('sqll', models.SmallIntegerField(default=0)),
                ('python', models.SmallIntegerField(default=0)),
                ('first_tag', models.CharField(default='Others', max_length=20)),
                ('summa', models.TextField(default=None)),
                ('time', models.DateTimeField(default='2000-01-01 00:00:00')),
            ],
        ),
    ]
